import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'
import Box1 from '../components/Box1'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>JBTV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Captur Photography' message='I captur beautiful moments' />
      <Box1 />
      <div className='bg-2 h-screen bg-fixed bg-center bg-cover'></div>
      <div className='bg-3 h-screen bg-fixed bg-center bg-cover'></div>
      {/*<Slider slides={SliderData}/>*/}
    </>
  )
}
