import React, { useEffect } from "react";
import Head from "next/head";
import Hero from "../components/Hero";
import { SliderData } from "../components/SliderData";
import Events from "../components/Events";
import Gallery from "../components/Gallery";
import Jbtv from "../components/Jbtv";
import Bureau from "../components/Bureau";
import Histoire from "../components/Histoire";

import Aos from "aos";
import "aos/dist/aos.css";

export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 3000 });
  }, []);

  return (
    <>
      <Head>
        <title>JBTV - ECE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="" message="" />
      <div>
        <Events slides={SliderData} />
      </div>
      <div className="bg-2 height bg-fixed bg-center bg-cover"></div>
      <Gallery className="hidd" />
      <div className="bg-3 height bg-fixed bg-center bg-cover"></div>
      <Jbtv className="hidd" />
      <div className="bg-4 height bg-fixed bg-center bg-cover"></div>
      <Bureau className="hidd" />
      <div className="bg-5 height bg-fixed bg-center bg-cover"></div>
      <Histoire className="hidd" />
    </>
  );
}
