import React, { useState } from "react";
import Image from "next/image";

const Box1 = () => {
  return (
    <div className="p-10">
      <h1 className="font-bold text-4xl pb-5">Box1</h1>
      <p className="pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sagittis sed nunc quis maximus. Suspendisse potenti. Nulla vulputate leo sed quam ornare auctor. Aliquam efficitur, tortor ac bibendum vehicula, orci mauris scelerisque nulla, ac facilisis arcu massa ut sem. Donec eu ultricies sapien. Duis egestas lectus arcu, a efficitur sapien lacinia eget. Vivamus tellus lacus, volutpat non augue eget, ultricies pharetra urna. Vestibulum tincidunt volutpat lacus sit amet luctus. Nunc laoreet diam ligula, faucibus accumsan metus ullamcorper nec. Duis volutpat metus urna, in ultrices augue blandit eu. In hac habitasse platea dictumst. Praesent pharetra nec massa non auctor. Praesent egestas efficitur dignissim. Curabitur tristique, orci eget interdum gravida, massa justo tempus dolor, eget fermentum nisl purus nec dui. Quisque mollis varius dui, sit amet ullamcorper leo rutrum vitae. Donec urna sapien, tristique sed quam ac, consectetur ornare tortor. Aenean molestie sem vel urna condimentum luctus. Praesent condimentum nunc eu dolor volutpat blandit. Aliquam commodo, ante id tempus commodo, purus velit accumsan nulla, eget efficitur mauris neque vel justo. Nulla vitae ultricies magna. Morbi mi odio, maximus a auctor vitae, pellentesque nec nisi. Aenean egestas pretium tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
      <p className="pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sagittis sed nunc quis maximus. Suspendisse potenti. Nulla vulputate leo sed quam ornare auctor. Aliquam efficitur, tortor ac bibendum vehicula, orci mauris scelerisque nulla, ac facilisis arcu massa ut sem. Donec eu ultricies sapien. Duis egestas lectus arcu, a efficitur sapien lacinia eget. Vivamus tellus lacus, volutpat non augue eget, ultricies pharetra urna. Vestibulum tincidunt volutpat lacus sit amet luctus. Nunc laoreet diam ligula, faucibus accumsan metus ullamcorper nec. Duis volutpat metus urna, in ultrices augue blandit eu. In hac habitasse platea dictumst. Praesent pharetra nec massa non auctor. Praesent egestas efficitur dignissim. Curabitur tristique, orci eget interdum gravida, massa justo tempus dolor, eget fermentum nisl purus nec dui. Quisque mollis varius dui, sit amet ullamcorper leo rutrum vitae. Donec urna sapien, tristique sed quam ac, consectetur ornare tortor. Aenean molestie sem vel urna condimentum luctus. Praesent condimentum nunc eu dolor volutpat blandit. Aliquam commodo, ante id tempus commodo, purus velit accumsan nulla, eget efficitur mauris neque vel justo. Nulla vitae ultricies magna. Morbi mi odio, maximus a auctor vitae, pellentesque nec nisi. Aenean egestas pretium tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sagittis sed nunc quis maximus. Suspendisse potenti. Nulla vulputate leo sed quam ornare auctor. Aliquam efficitur, tortor ac bibendum vehicula, orci mauris scelerisque nulla, ac facilisis arcu massa ut sem. Donec eu ultricies sapien. Duis egestas lectus arcu, a efficitur sapien lacinia eget. Vivamus tellus lacus, volutpat non augue eget, ultricies pharetra urna. Vestibulum tincidunt volutpat lacus sit amet luctus. Nunc laoreet diam ligula, faucibus accumsan metus ullamcorper nec. Duis volutpat metus urna, in ultrices augue blandit eu. In hac habitasse platea dictumst. Praesent pharetra nec massa non auctor. Praesent egestas efficitur dignissim. Curabitur tristique, orci eget interdum gravida, massa justo tempus dolor, eget fermentum nisl purus nec dui. Quisque mollis varius dui, sit amet ullamcorper leo rutrum vitae. Donec urna sapien, tristique sed quam ac, consectetur ornare tortor. Aenean molestie sem vel urna condimentum luctus. Praesent condimentum nunc eu dolor volutpat blandit. Aliquam commodo, ante id tempus commodo, purus velit accumsan nulla, eget efficitur mauris neque vel justo. Nulla vitae ultricies magna. Morbi mi odio, maximus a auctor vitae, pellentesque nec nisi. Aenean egestas pretium tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
    </div>
  )
};

export default Box1;